name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Typecheck
        run: npx nx run-many -t typecheck
        env:
          NX_SYNC_SKIP: true

      - name: Test
        run: npx nx run-many -t test
        env:
          NX_SYNC_SKIP: true

      - name: Build
        run: npx nx run-many -t build
        env:
          NX_SYNC_SKIP: true
